apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: financial-agent-dev
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ENABLE_DEBUG
          value: "true"
        - name: CORS_ORIGINS
          value: '["*"]'
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: url
        # Dev-specific resource limits
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"