apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: financial-agent-dev
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: REACT_APP_DEBUG
          value: "true"
        - name: REACT_APP_API_URL
          value: "http://backend-service:8000"
        # Dev-specific resource limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"