apiVersion: batch/v1
kind: CronJob
metadata:
  name: reconcile-transactions
  labels:
    app: reconcile-transactions
    component: worker
spec:
  # Run every 10 minutes
  schedule: "*/10 * * * *"
  # Keep last 3 successful and 1 failed job for debugging
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  # Prevent concurrent runs (wait for previous job to complete)
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # Clean up completed jobs after 1 hour
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          labels:
            app: reconcile-transactions
            component: worker
        spec:
          serviceAccountName: klinematrix-sa
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - name: reconcile
            image: klinematrix/backend:test
            imagePullPolicy: Always
            command:
            - python
            - -m
            - src.workers.reconcile_transactions
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                  - ALL
            volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/.cache
            - name: home-cache
              mountPath: /home/app/.cache
            # Environment variables defined in overlays
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "200m"
          volumes:
          - name: tmp
            emptyDir: {}
          - name: cache
            emptyDir: {}
          - name: home-cache
            emptyDir: {}
