apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: financial-agent-dev
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP