apiVersion: v1
kind: Service
metadata:
  name: langfuse-clickhouse
  labels:
    app: langfuse-clickhouse
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: native
  selector:
    app: langfuse-clickhouse
