apiVersion: batch/v1
kind: Job
metadata:
  name: langfuse-db-init
  labels:
    app: langfuse
    component: db-init
spec:
  ttlSecondsAfterFinished: 600  # Clean up after 10 minutes
  template:
    metadata:
      labels:
        app: langfuse
        component: db-init
    spec:
      serviceAccountName: klinematrix-sa
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 999  # postgres user
        fsGroup: 999
      containers:
      - name: db-init
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POLARDB_HOST
          value: "pc-bp141ar06fos11131.rwlb.rds.aliyuncs.com"
        - name: POLARDB_PORT
          value: "5432"
        - name: POLARDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: langfuse-secrets
              key: polardb-password
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: langfuse-secrets
              key: polardb-password
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: init-script
          mountPath: /scripts
        command:
        - sh
        - -c
        - |
          set -e
          echo "Checking connection to PolarDB..."
          psql -h $POLARDB_HOST -p $POLARDB_PORT -U postgres -d postgres -c "SELECT version();"

          echo "Creating database 'langfuse' if not exists..."
          psql -h $POLARDB_HOST -p $POLARDB_PORT -U postgres -d postgres -c "CREATE DATABASE langfuse;" || echo "Database already exists"

          echo "Creating user 'langfuseadmin' if not exists..."
          psql -h $POLARDB_HOST -p $POLARDB_PORT -U postgres -d postgres -c "CREATE USER langfuseadmin WITH PASSWORD '$(cat /var/run/secrets/polardb-password)';" || echo "User already exists"

          echo "Granting privileges..."
          psql -h $POLARDB_HOST -p $POLARDB_PORT -U postgres -d postgres -c "GRANT ALL PRIVILEGES ON DATABASE langfuse TO langfuseadmin;"

          echo "Database initialization complete!"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: init-script
        emptyDir: {}
