title: Agent Chat Flow with Database & Log Verification
slug: agent-flow-e2e
starred: true
tags:
  - agent
  - chat
  - e2e
  - database
  - logs
estimatedDuration: 180
steps:
  - id: '01'
    title: Login to Application
    file: 01-login-to-application.md
  - id: '02'
    title: Navigate to Chat and Send Agent Query
    file: 02-navigate-to-chat-and-send-agent-query.md
  - id: '03'
    title: Verify Streaming Response with Tool Execution
    file: 03-verify-streaming-response-with-tool-execution.md
  - id: '04'
    title: Verify Backend Logs Show Tool Execution
    file: 04-verify-backend-logs-show-tool-execution.md
  - id: '05'
    title: Verify Database Message Records
    file: 05-verify-database-message-records.md
  - id: '06'
    title: Verify Database Tool Execution Records
    file: 06-verify-database-tool-execution-records.md
  - id: '07'
    title: Verify Chat History Persistence
    file: 07-verify-chat-history-persistence.md
totalRuns: 1
passCount: 1
failCount: 0
lastRun: '2025-12-26T07:52:57.532Z'
lastResult: pass
avgDuration: 58000
