title: 'Story 2.8: Put/Call Ratio Tool with Redis Cache'
slug: story-2-8-pcr-tool-cache
starred: false
tags:
  - ai-tools
  - redis
  - pcr
  - cache
estimatedDuration: 120
steps:
  - id: '01'
    title: Verify backend health and Redis connection
    file: 01-verify-backend-health-and-redis-connection.md
  - id: '02'
    title: Clear PCR cache and verify cache miss
    file: 02-clear-pcr-cache-and-verify-cache-miss.md
  - id: '03'
    title: Invoke PCR tool via chat API - first call (cache miss)
    file: 03-invoke-pcr-tool-via-chat-api-first-call-cache-miss.md
  - id: '04'
    title: Verify Redis cache populated after first call
    file: 04-verify-redis-cache-populated-after-first-call.md
  - id: '05'
    title: Invoke PCR tool again - verify cache hit
    file: 05-invoke-pcr-tool-again-verify-cache-hit.md
  - id: '06'
    title: Verify PCR logic with different symbols
    file: 06-verify-pcr-logic-with-different-symbols.md
totalRuns: 1
passCount: 1
failCount: 0
lastRun: '2025-12-31T02:29:04.069Z'
lastResult: pass
avgDuration: 180000
