apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: financial-agent-ingress
  namespace: financial-agent-dev
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - financial-agent-dev.koreacentral.cloudapp.azure.com
    secretName: financial-agent-tls
  rules:
  - host: financial-agent-dev.koreacentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80