apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: financial-agent-dev
data:
  redis.conf: |
    # Redis configuration for Financial Agent Dev
    bind 0.0.0.0
    port 6379

    # Memory management
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Persistence
    appendonly yes
    appendfsync everysec

    # Security
    requirepass ${REDIS_PASSWORD}

    # Performance
    tcp-keepalive 300
    timeout 0

    # Logging
    loglevel notice